//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.27 at 11:07:45 AM IST 
//


package com.amazonservices.mws.products.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.amazonservices.mws.client.AbstractMwsObject;
import com.amazonservices.mws.client.MwsReader;
import com.amazonservices.mws.client.MwsWriter;


/**
 * <p>Java class for DimensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DimensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Height" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="Length" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="Width" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="Weight" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DecimalWithUnits" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ns2:DimensionType", propOrder = {
    "height",
    "length",
    "width",
    "weight"
})
public class DimensionType extends AbstractMwsObject{

    @XmlElement(name = "ns2:Height")
    protected DecimalWithUnits height;
    @XmlElement(name = "ns2:Length")
    protected DecimalWithUnits length;
    @XmlElement(name = "ns2:Width")
    protected DecimalWithUnits width;
    @XmlElement(name = "ns2:Weight")
    protected DecimalWithUnits weight;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalWithUnits }
     *     
     */
    public DecimalWithUnits getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalWithUnits }
     *     
     */
    public void setHeight(DecimalWithUnits value) {
        this.height = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalWithUnits }
     *     
     */
    public DecimalWithUnits getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalWithUnits }
     *     
     */
    public void setLength(DecimalWithUnits value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalWithUnits }
     *     
     */
    public DecimalWithUnits getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalWithUnits }
     *     
     */
    public void setWidth(DecimalWithUnits value) {
        this.width = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalWithUnits }
     *     
     */
    public DecimalWithUnits getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalWithUnits }
     *     
     */
    public void setWeight(DecimalWithUnits value) {
        this.weight = value;
    }

    @Override
   	public void readFragmentFrom(MwsReader r) {
   		height = r.read("ns2:Height", DecimalWithUnits.class);
   		length = r.read("ns2:Length", DecimalWithUnits.class);
   		width = r.read("ns2:Width", DecimalWithUnits.class);
   		weight = r.read("ns2:Weight", DecimalWithUnits.class);
   	}

   	@Override
   	public void writeFragmentTo(MwsWriter w) {
   		w.write("Height", height);
        w.write("Length", length);
        w.write("Width", width);
        w.write("Weight", weight);
   	}

   	public DimensionType(DecimalWithUnits height, DecimalWithUnits length, DecimalWithUnits width,
			DecimalWithUnits weight) {
		super();
		this.height = height;
		this.length = length;
		this.width = width;
		this.weight = weight;
	}

   	public DimensionType() {
		super();
	}
   	
	@Override
   	public void writeTo(MwsWriter w) {
   		w.write("http://mws.amazonservices.com/schema/Products/2011-10-01", "DimensionType",this);
   	}
}
